# Generated by Django 4.0.6 on 2022-07-27 10:35

from django.db import migrations

from operation.models import StationLine
from spotting.enums import SpottingEventType
from spotting.models import Event


def fix_stations(apps, schema_editor):
    events = Event.objects.filter(type=SpottingEventType.BETWEEN_STATIONS)
    for event in events:
        event.origin_station_id = StationLine.objects.get(id=event.origin_station_id).id
        event.destination_station_id = StationLine.objects.get(
            id=event.destination_station_id
        ).id

    Event.objects.bulk_update(events, ["origin_station_id", "destination_station_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("spotting", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=fix_stations,
            reverse_code=migrations.RunPython.noop,
        )
    ]
