# Generated by Django 4.0.6 on 2022-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotting", "0002_fix_incorrect_spotting_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_SERVICE", "In Service"),
                    ("NOT_SPOTTED", "Not Spotted"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("MARRIED", "Married"),
                    ("TESTING", "Testing"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=32,
            ),
        ),
    ]
