# Generated by Django 4.1 on 2022-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotting", "0003_event_is_anonymous_alter_event_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="spotting_event_value_relevant",
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOT", "Depot"),
                    ("LOCATION", "Location"),
                    ("BETWEEN_STATIONS", "Between Stations"),
                    ("JUST_SPOTTING", "Just Spotting"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("type", "BETWEEN_STATIONS"),
                        ("origin_station__isnull", False),
                        ("destination_station__isnull", False),
                        ("location__isnull", True),
                        models.Q(
                            ("origin_station", models.F("destination_station")),
                            _negated=True,
                        ),
                        models.Q(
                            ("destination_station", models.F("origin_station")),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("type", "LOCATION"),
                        ("origin_station__isnull", True),
                        ("destination_station__isnull", True),
                        ("location__isnull", False),
                    ),
                    models.Q(
                        ("type__in", ["DEPOT", "JUST_SPOTTING"]),
                        ("origin_station__isnull", True),
                        ("destination_station__isnull", True),
                        ("location__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="spotting_event_value_relevant",
            ),
        ),
    ]
