# Generated by Django 4.1 on 2022-08-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("operation", "0001_initial"),
        ("spotting", "0004_remove_event_spotting_event_value_relevant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.user"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="operation.vehicle"
            ),
        ),
    ]
