# Generated by Django 4.1.3 on 2022-11-13 17:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotting", "0007_create_eventread"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=None,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "altitude_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=None,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=None,
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="event",
            name="spotting_event_value_relevant",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("type", "BETWEEN_STATIONS"),
                        ("origin_station__isnull", False),
                        ("destination_station__isnull", False),
                        models.Q(
                            ("origin_station", models.F("destination_station")),
                            _negated=True,
                        ),
                        models.Q(
                            ("destination_station", models.F("origin_station")),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("type__in", ["DEPOT", "JUST_SPOTTING", "LOCATION"]),
                        ("origin_station__isnull", True),
                        ("destination_station__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="spotting_event_value_relevant",
            ),
        ),
        migrations.AddField(
            model_name="locationevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotting.event"
            ),
        ),
    ]
