# Generated by Django 4.1.3 on 2022-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotting", "0008_locationevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationevent",
            name="altitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=None, max_digits=12, null=True
            ),
        ),
    ]
