# Generated by Django 4.1.3 on 2022-11-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotting", "0009_locationevent_altitude"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="spotting_event_value_relevant",
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOT", "Depot"),
                    ("LOCATION", "Location"),
                    ("BETWEEN_STATIONS", "Between Stations"),
                    ("JUST_SPOTTING", "Just Spotting"),
                    ("AT_STATION", "At Station"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("type", "BETWEEN_STATIONS"),
                        ("origin_station__isnull", False),
                        ("destination_station__isnull", False),
                        models.Q(
                            ("origin_station", models.F("destination_station")),
                            _negated=True,
                        ),
                        models.Q(
                            ("destination_station", models.F("origin_station")),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("type", "AT_STATION"),
                        ("origin_station__isnull", False),
                        ("destination_station__isnull", True),
                    ),
                    models.Q(
                        ("type__in", ["DEPOT", "JUST_SPOTTING", "LOCATION"]),
                        ("origin_station__isnull", True),
                        ("destination_station__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="spotting_event_value_relevant",
            ),
        ),
    ]
