# Generated by Django 4.2.7 on 2023-11-10 11:06

import django_choices_field.fields
from django.db import migrations

import spotting.enums


class Migration(migrations.Migration):
    dependencies = [
        ("spotting", "0014_alter_event_status_alter_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="wheel_status",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("FRESH", "Fresh"),
                    ("NEAR_PERFECT", "Near Perfect"),
                    ("FLAT", "Flat"),
                    ("WORN_OUT", "Worn Out"),
                    ("WORRYING", "Worrying"),
                ],
                choices_enum=spotting.enums.SpottingWheelStatus,
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
