# Generated by Django 4.2.10 on 2024-03-18 19:24

from django.db import migrations

from spotting.enums import SpottingDataSource


def add_spotting_event_source(apps, schema_editor):
    EventSource = apps.get_model("spotting", "EventSource")
    EventSource.objects.bulk_create(
        [
            EventSource(name=SpottingDataSource.SITE),
            EventSource(name=SpottingDataSource.TELEGRAM),
        ]
    )


def add_spotting_event_source_to_event(apps, schema_editor):
    Event = apps.get_model("spotting", "Event")
    EventSource = apps.get_model("spotting", "EventSource")

    event_source = EventSource.objects.filter(name=SpottingDataSource.SITE).first()

    Event.objects.all().update(data_source_id=event_source)


class Migration(migrations.Migration):
    dependencies = [
        ("spotting", "0016_eventsource_event_data_source"),
    ]

    operations = [
        migrations.RunPython(
            code=add_spotting_event_source,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=add_spotting_event_source_to_event,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
