# Generated by Django 4.1.6 on 2023-02-14 16:45

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jejak", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityBusRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("bus", models.CharField(max_length=64)),
                ("bus_id", models.BigIntegerField()),
                ("accessibility_id", models.BigIntegerField()),
                ("is_oku_friendly", models.BooleanField()),
            ],
            options={
                "db_table": "view_accessibilitybusrange",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BusProviderRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("bus", models.CharField(max_length=64)),
                ("bus_id", models.BigIntegerField()),
                ("provider", models.CharField(max_length=64)),
                ("provider_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "view_busproviderrange",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BusRouteRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("bus", models.CharField(max_length=64)),
                ("bus_id", models.BigIntegerField()),
                ("route", models.CharField(max_length=64)),
                ("route_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "view_busrouterange",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BusStopBusRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("bus", models.CharField(max_length=64)),
                ("bus_id", models.BigIntegerField()),
                ("bus_stop", models.CharField(max_length=64)),
                ("bus_stop_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "view_busstopbusrange",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CaptainBusRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("bus", models.CharField(max_length=64)),
                ("bus_id", models.BigIntegerField()),
                ("captain", models.CharField(max_length=64)),
                ("captain_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "view_captainbusrange",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CaptainProviderRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("provider_id", models.BigIntegerField()),
                ("captain", models.CharField(max_length=64)),
                ("captain_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "view_captainproviderrange",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineStatusBusRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("bus", models.CharField(max_length=64)),
                ("bus_id", models.BigIntegerField()),
                ("engine_status", models.CharField(max_length=64)),
                ("engine_status_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "view_enginestatusbusrange",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TripRevBusRangeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default_bounds="[]"
                    ),
                ),
                ("bus", models.CharField(max_length=64)),
                ("bus_id", models.BigIntegerField()),
                ("trip_rev", models.CharField(max_length=64)),
                ("trip_rev_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "view_triprevbusrange",
                "managed": False,
            },
        ),
    ]
