# Generated by Django 4.1.5 on 2023-01-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jejak", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                fields=("identifier", "bus", "provider"),
                name="jejak_trip_trip_bus_provider_unique",
            ),
        ),
    ]
