# Generated by Django 4.1.5 on 2023-02-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jejak", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="identifier",
            field=models.CharField(max_length=64),
        ),
    ]
