# Generated by Django 5.2.17 on 2026-08-18 21:07

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jejak", "0002_accessibilitybusrangeview_busproviderrangeview_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accessibilitybusrange",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["bus", "dt_range"], name="idx_accessbusrange_bus_range"
            ),
        ),
        migrations.AddIndex(
            model_name="busproviderrange",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["bus", "dt_range"], name="idx_busproviderrange_bus_range"
            ),
        ),
        migrations.AddIndex(
            model_name="busrouterange",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["bus", "dt_range"], name="idx_busrouterange_bus_range"
            ),
        ),
        migrations.AddIndex(
            model_name="busstopbusrange",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["bus", "dt_range"], name="idx_busstopbusrange_bus_range"
            ),
        ),
        migrations.AddIndex(
            model_name="captainbusrange",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["bus", "dt_range"], name="idx_captainbusrange_bus_range"
            ),
        ),
        migrations.AddIndex(
            model_name="enginestatusbusrange",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["bus", "dt_range"], name="idx_engstatbusrange_bus_range"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["bus", "-dt_gps"], name="idx_location_bus_dtgps"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["bus", "-dt_received"], name="idx_location_bus_dtreceived"
            ),
        ),
        migrations.AddIndex(
            model_name="triprevbusrange",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["bus", "dt_range"], name="idx_triprevbusrange_bus_range"
            ),
        ),
    ]
