repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-json
      - id: check-case-conflict
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          [
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--line-width=88",
            "--ensure-newline-before-comments",
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --exclude=*/*migrations/*, testproject/testproject/settings/*, __init__.py, apps.py
          - --ignore=E203, E266, E501, W503
          - --max-complexity=18
          - --max-line-length=88
        exclude: "__init__.py"
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  #   rev: v1.1.2
  #   hooks:
  #     - id: markdown-toc
  #       # optional custom config:
  #       args: [--indent, "    ", -i]
  #     - id: dockerfile_lint
  #       # optional custom config:
  #       args: [--json, --verbose, --dockerfile]
  - repo: https://github.com/kwongtn/pipfile-sort
    rev: v0.3.1
    hooks:
      - id: pipfile-sort
