version: "3"

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - .:/code
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  web:
    image: nginx:alpine
    env_file:
      - secrets.dev.env
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/local:/etc/nginx/templates/
      - ./static:/code/static
    depends_on:
      - app
    restart: always

  app:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    env_file:
      - secrets.dev.env
    command: bash run_app.sh
    volumes:
      - .:/code
      - ./../.firebase/rosak-7223b-firebase-adminsdk-8hcki-f2e0ee7994.json:/google-application-credential.json
    expose:
      - "8001"
    depends_on:
      - db
    restart: always
