services:
  db:
    image: postgis/postgis:17-3.5-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - .:/code
    restart: unless-stopped

  web:
    image: nginx:alpine
    env_file:
      - secrets.dev.env
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/local:/etc/nginx/templates/
      - ./static:/code/static
    depends_on:
      - app
    restart: unless-stopped

  app: &app
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    env_file:
      - secrets.dev.env
    command: bash run_app.sh
    volumes:
      - .:/code
      - ./../.firebase/rosak-7223b-firebase-adminsdk-8hcki-f2e0ee7994.json:/google-application-credential.json
    expose:
      - "8001"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  celeryworker:
    <<: *app
    depends_on:
      - db
      - redis
    command: bash run_celery.sh

  celerybeat:
    <<: *app
    volumes:
      - .:/code
    env_file:
      - secrets.dev.env
    depends_on:
      - redis
      - db
    ports: []
    command: bash run_celery_beat.sh
