version: "3"

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - .:/code
    restart: always

  web:
    image: nginx:alpine
    env_file:
      - secrets.dev.env
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/local:/etc/nginx/templates/
      - ./static:/code/static
    depends_on:
      - app
    restart: always

  memcached:
    image: memcached:1.6.20-alpine
    expose:
      - "11211"
    restart: always

  app:
    &app
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    env_file:
      - secrets.dev.env
    command: bash run_app.sh
    volumes:
      - .:/code
      - ./../.firebase/rosak-7223b-firebase-adminsdk-8hcki-f2e0ee7994.json:/google-application-credential.json
    expose:
      - "8001"
    depends_on:
      - db
      - memcached
    restart: always

  redis:
    image: redis:7
    restart: always

  celeryworker:
    <<: *app
    depends_on:
      - db
      - memcached
      - redis
    command: bash run_celery.sh
    restart: no

  celerybeat:
    <<: *app
    volumes:
      - .:/code
    env_file:
      - secrets.dev.env
    depends_on:
      - redis
      - db
    ports: []
    command: bash run_celery_beat.sh
