version: "3"

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: always

  web:
    image: nginx:alpine
    env_file:
      - secrets.env
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/prod:/etc/nginx/templates/
      - ./static:/code/static
      - /etc/letsencrypt/live/lift-rosak.ddns.net:/cert/live/lift-rosak.ddns.net:ro
      - /etc/letsencrypt/archive/lift-rosak.ddns.net:/cert/archive/lift-rosak.ddns.net:ro
    depends_on:
      - app
    restart: always

  app:
    image: docker.io/kwongtn/rosak_backend:latest
    env_file:
      - secrets.env
    command: bash run_app.sh
    volumes:
      - ./google-application-credential.json:/google-application-credential.json
    expose:
      - "8001"
    depends_on:
      - db
    restart: always
