version: "3"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: always

  web:
    image: nginx:latest
    env_file:
      - secrets.dev.env
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/local:/etc/nginx/templates/
      - ./static:/code/static
    depends_on:
      - app

  app:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    image: rosak-backend-app:latest
    env_file:
      - secrets.dev.env
    command: bash run_app.sh
    volumes:
      - .:/code
    expose:
      - "8001"
    depends_on:
      - db
