# Generated by Django 5.2.17 on 2026-08-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advanced_filters", "0003_auto_20180610_0718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedfilter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
