# Generated by Django 4.1.4 on 2022-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlptf", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.ManyToManyField(through="mlptf.UserBadge", to="mlptf.badge"),
        ),
    ]
