# Generated by Django 4.1.7 on 2023-03-07 13:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_user_badges"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJejakTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MONTHLY_RENEWAL", "Monthly Renewal"),
                            ("TOP_UP", "Top Up"),
                            ("COUNT_ROWS", "Count Rows"),
                            ("BUS_LOCATION_HISTORY", "Bus Location History"),
                            ("BANDWIDTH", "Bandwidth"),
                        ],
                        max_length=32,
                    ),
                ),
                ("credit_change", models.IntegerField()),
                ("details", models.TextField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
