# Generated by Django 4.1.7 on 2023-03-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_userjejaktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjejaktransaction",
            name="credit_type",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("FREE", "Free"), ("SPECIAL", "Special")],
                default="PAID",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
