# Generated by Django 4.2.3 on 2023-07-16 16:23

from django.db import migrations, models

import common.imgur_storage


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_temporarymedia_can_retry_temporarymedia_fail_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="height",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="width",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.ImageField(
                storage=common.imgur_storage.ImgurStorage(),
                upload_to="rosak_local_kwongtn",
            ),
        ),
    ]
