# Generated by Django 4.2.3 on 2023-07-24 11:10

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_alter_temporarymedia_upload_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("TRUSTED_MEDIA_UPLOADER", "Trusted Media Uploader")],
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="temporarymedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("CLEARED", "Cleared"),
                    ("TRUSTED_CLEARED", "Trusted Cleared"),
                    ("OVERRIDE_CLEARED", "Override Cleared"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("RETRY_ELAPSED", "Retry Elapsed"),
                    ("INVALID_UPLOAD", "Invalid Upload"),
                    ("TO_DELETE", "To Delete"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="UserClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "clearance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.clearance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="clearance",
            name="users",
            field=models.ManyToManyField(
                through="common.UserClearance", to="common.user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="clearances",
            field=models.ManyToManyField(
                through="common.UserClearance", to="common.clearance"
            ),
        ),
        migrations.RemoveField(
            model_name="temporarymedia",
            name="can_retry",
        ),
    ]
