# Generated by Django 4.2.3 on 2023-08-13 12:52

from django.db import migrations, models

import common.imgur_field
import common.imgur_storage


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_clearance_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="content_type",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="file_id",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="file_name",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="message_id",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="file",
            field=common.imgur_field.ImgurField(
                blank=True,
                default=None,
                height_field="height",
                null=True,
                storage=common.imgur_storage.ImgurStorage(),
                upload_to="rosak_local_kwongtn",
                width_field="width",
            ),
        ),
    ]
