# Generated by Django 4.2.11 on 2024-05-17 18:05

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import common.imgur_field
import common.imgur_storage


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_user_telegram_id_alter_media_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=common.imgur_field.ImgurField(
                blank=True,
                default=None,
                height_field="height",
                null=True,
                storage=common.imgur_storage.ImgurStorage(),
                upload_to="rosak_local_kwongtn",
                width_field="width",
            ),
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("IMAGE_UPLOAD", "Image Upload")],
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("enabled", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
