# Generated by Django 4.2.11 on 2024-05-17 18:13

from django.db import migrations


def add_data(apps, schema_editor):
    from common.enums import FeatureFlagType
    from common.models import FeatureFlag as FeatureFlagModelType

    FeatureFlag: FeatureFlagModelType = apps.get_model("common", "FeatureFlag")

    FeatureFlag.objects.bulk_create(
        [FeatureFlag(name=j) for j in [i[0] for i in FeatureFlagType.choices]],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_alter_media_file_featureflag"),
    ]

    operations = [
        migrations.RunPython(
            code=add_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
