# Generated by Django 4.2.13 on 2024-06-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0016_featureflag_alter_media_file_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarymedia",
            name="discord_res",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="temporarymedia",
            name="uploaded_discord",
            field=models.BooleanField(default=False),
        ),
    ]
