# Generated by Django 5.2.17 on 2026-08-18 16:47

from django.db import migrations

import common.imgur_field
import common.imgur_storage


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_temporarymedia_discord_res_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=common.imgur_field.ImgurField(
                blank=True,
                default=None,
                height_field="height",
                null=True,
                storage=common.imgur_storage.ImgurStorage(),
                upload_to="media",
                width_field="width",
            ),
        ),
    ]
