# Generated by Django 5.2.17 on 2026-08-22 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_vote_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="common.user",
            ),
        ),
    ]
