# Generated by Django 5.2.17 on 2026-09-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_alter_vote_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="caption",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="media",
            name="duration",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="content_type",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="temporarymedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("CLEARED", "Cleared"),
                    ("TRUSTED_CLEARED", "Trusted Cleared"),
                    ("OVERRIDE_CLEARED", "Override Cleared"),
                    ("BLOCKED", "Blocked"),
                    ("PENDING", "Pending"),
                    ("RETRY_ELAPSED", "Retry Elapsed"),
                    ("INVALID_UPLOAD", "Invalid Upload"),
                    ("TO_DELETE", "To Delete"),
                    ("AWAITING_REVIEW", "Awaiting Review"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
