# Generated by Django 4.2.10 on 2024-03-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spotting", "0016_eventsource_event_data_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(choices=[(0, "Inbound"), (1, "Outbound")]),
                ),
                ("payload", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="TelegramSpottingEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotting_event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_logs",
                        to="spotting.event",
                    ),
                ),
                (
                    "telegram_log",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_logs",
                        to="telegram_provider.telegramlogs",
                    ),
                ),
            ],
        ),
    ]
