# Generated by Django 4.2.11 on 2024-03-31 10:08

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_provider", "0002_alter_telegramspottingeventlog_telegram_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramlogs",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="telegramlogs",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
