# Generated by Django 5.2.17 on 2026-08-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_provider", "0003_telegramlogs_created_telegramlogs_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramlogs",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="telegramlogs",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="telegramlogs",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
