# Generated by Django 4.2.10 on 2024-02-24 19:34

import colorfield.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import model_utils.fields
from django.db import migrations, models

import operation.enums

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# operation.migrations.0005_vehicleline_many_to_many_data
#
# AUTHOR NOTE: No longer required as of 2022-08-14.


class Migration(migrations.Migration):
    replaces = [
        ("operation", "0001_initial"),
        ("operation", "0002_alter_asset_options_alter_line_options_and_more"),
        ("operation", "0003_add_vehicle_vehicle_type_related_name"),
        ("operation", "0004_vehicleline_many_to_many_db0"),
        ("operation", "0005_vehicleline_many_to_many_data"),
        ("operation", "0006_vehicleline_many_to_many_db1"),
        ("operation", "0007_alter_station_options_vehicle_nickname_and_more"),
        (
            "operation",
            "0008_stationline_override_internal_representation_constraint_and_more",
        ),
        ("operation", "0009_alter_vehicleline_line_alter_vehicleline_vehicle"),
        ("operation", "0010_asset_operation_a_short_d_88fa17_btree_and_more"),
        (
            "operation",
            "0011_stationline_operation_stationline_unique_line_internal_representation",
        ),
        ("operation", "0012_alter_vehicle_status"),
        ("operation", "0013_line_status"),
        ("operation", "0014_line_official_numbering"),
        ("operation", "0015_alter_line_display_color_vehicle_wheel_status"),
    ]

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "officialid",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("long_description", models.TextField(blank=True, default="")),
                (
                    "asset_type",
                    models.TextField(
                        choices=[("ESCALATOR", "Escalator"), ("LIFT", "Lift")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("display_name", models.TextField()),
                (
                    "display_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("display_name", models.TextField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StationMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.media"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operation.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("display_name", models.TextField()),
                (
                    "internal_representation",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True, unique=True
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operation.line"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operation.station",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["internal_representation"],
            },
        ),
        migrations.AddField(
            model_name="station",
            name="lines",
            field=models.ManyToManyField(
                through="operation.StationLine", to="operation.line"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="medias",
            field=models.ManyToManyField(
                through="operation.StationMedia", to="common.media"
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="stations",
            field=models.ManyToManyField(
                through="operation.StationLine", to="operation.station"
            ),
        ),
        migrations.CreateModel(
            name="AssetMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operation.asset",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.media"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="medias",
            field=models.ManyToManyField(
                through="operation.AssetMedia", to="common.media"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.station"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDER_MAINTENANCE", "Under Maintenance"),
                    ("IN_OPERATION", "In Operation"),
                ],
                default="IN_OPERATION",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "internal_name",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["officialid"]},
        ),
        migrations.AlterModelOptions(
            name="line",
            options={"ordering": ["code"]},
        ),
        migrations.AlterField(
            model_name="asset",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="operation.station",
            ),
        ),
        migrations.AlterField(
            model_name="stationline",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="station_lines",
                to="operation.line",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identification_no", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_SERVICE", "In Service"),
                            ("NOT_SPOTTED", "Not Spotted"),
                            ("DECOMMISSIONED", "Decommissioned"),
                            ("MARRIED", "Married"),
                            ("TESTING", "Testing"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="operation.line",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="operation.vehicletype",
                    ),
                ),
                (
                    "in_service_since",
                    models.DateField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "ordering": ["identification_no"],
            },
        ),
        migrations.CreateModel(
            name="VehicleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="line",
            name="vehicles_new",
            field=models.ManyToManyField(
                related_name="lines",
                through="operation.VehicleLine",
                to="operation.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="lines_new",
            field=models.ManyToManyField(
                related_name="vehicles",
                through="operation.VehicleLine",
                to="operation.line",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.line"
            ),
        ),
        migrations.AddField(
            model_name="vehicleline",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.line"
            ),
        ),
        migrations.AddField(
            model_name="vehicleline",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.vehicle"
            ),
        ),
        # migrations.RunPython(
        #     code=operation.migrations.0005_vehicleline_many_to_many_data.forwards_func,
        #     reverse_code=django.db.migrations.operations.special.RunPython.noop,
        # ),
        migrations.RenameField(
            model_name="line",
            old_name="vehicles_new",
            new_name="vehicles",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="line",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="lines_new",
            new_name="lines",
        ),
        migrations.AlterField(
            model_name="line",
            name="vehicles",
            field=models.ManyToManyField(
                related_name="vehicle_lines",
                through="operation.VehicleLine",
                to="operation.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="lines",
            field=models.ManyToManyField(
                related_name="line_vehicles",
                through="operation.VehicleLine",
                to="operation.line",
            ),
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["display_name"]},
        ),
        migrations.AddField(
            model_name="vehicle",
            name="nickname",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="internal_name",
            field=models.CharField(
                blank=True, default=None, max_length=16, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="stationline",
            name="override_internal_representation_constraint",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="line",
            name="code",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="stationline",
            name="internal_representation",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("officialid",), name="operation_asset_unique_officialid"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetmedia",
            constraint=models.UniqueConstraint(
                fields=("asset", "media"),
                name="operation_assetmedia_unique_asset_media",
            ),
        ),
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("code",), name="operation_line_unique_line_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("display_name",), name="operation_line_unique_display_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("display_name",), name="operation_station_unique_display_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="stationline",
            constraint=models.UniqueConstraint(
                fields=("station", "line"),
                name="operation_stationline_unique_station_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="stationline",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("override_internal_representation_constraint", False),
                        ("internal_representation__isnull", False),
                    )
                ),
                fields=("internal_representation",),
                name="operation_stationline_unique_internal_representation",
            ),
        ),
        migrations.AddConstraint(
            model_name="stationmedia",
            constraint=models.UniqueConstraint(
                fields=("station", "media"),
                name="operation_stationmedia_unique_station_media",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                fields=("identification_no", "vehicle_type"),
                name="operation_vehicle_unique_identification_no_vehicle_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleline",
            constraint=models.UniqueConstraint(
                fields=("vehicle", "line"),
                name="operation_vehicleline_unique_vehicle_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicletype",
            constraint=models.UniqueConstraint(
                fields=("internal_name",),
                name="operation_vehicletype_unique_internal_name",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleline",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="operation.line"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleline",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="operation.vehicle"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["short_description"], name="operation_a_short_d_88fa17_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["long_description"], name="operation_a_long_de_67af59_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="line",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["code"], name="operation_l_code_370814_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="line",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["display_name"], name="operation_l_display_e3a69a_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="line",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["display_color"], name="operation_l_display_857380_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["display_name"], name="operation_s_display_be1040_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="stationline",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["display_name"], name="operation_s_display_38ef0e_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="stationline",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["internal_representation"],
                name="operation_s_interna_a6acef_btree",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["identification_no"], name="operation_v_identif_d2fca9_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicletype",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["internal_name"], name="operation_v_interna_f3d30b_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicletype",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["display_name"], name="operation_v_display_e0fd1e_btree"
            ),
        ),
        migrations.AddConstraint(
            model_name="stationline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("internal_representation__isnull", False)),
                fields=("line", "internal_representation"),
                name="operation_stationline_unique_line_internal_representation",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_SERVICE", "In Service"),
                    ("NOT_SPOTTED", "Not Spotted"),
                    ("OUT_OF_SERVICE", "Out Of Service"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("MARRIED", "Married"),
                    ("TESTING", "Testing"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("TESTING", "Testing"),
                    ("DEFUNCT", "Defunct"),
                    ("ACTIVE", "Active"),
                    ("PARTIAL_ACTIVE", "Partial Active"),
                    ("PARTIAL_DISRUPTION", "Partial Disruption"),
                    ("TOTAL_DISRUPTION", "Total Disruption"),
                ],
                choices_enum=operation.enums.LineStatus,
                default="ACTIVE",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="official_numbering",
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="line",
            name="display_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="wheel_status",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("FRESH", "Fresh"),
                    ("NEAR_PERFECT", "Near Perfect"),
                    ("FLAT", "Flat"),
                    ("WORN_OUT", "Worn Out"),
                    ("WORRYING", "Worrying"),
                ],
                choices_enum=operation.enums.WheelStatus,
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
