# Generated by Django 4.0.5 on 2022-07-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("operation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.media"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="medias",
            field=models.ManyToManyField(
                through="operation.AssetMedia", to="common.media"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="medias",
            field=models.ManyToManyField(
                through="operation.StationMedia", to="common.media"
            ),
        ),
        migrations.AddField(
            model_name="stationmedia",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.station"
            ),
        ),
        migrations.AddField(
            model_name="assetmedia",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operation.asset"
            ),
        ),
        migrations.AddField(
            model_name="assetmedia",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="common.media"
            ),
        ),
    ]
