# Generated by Django 4.0.6 on 2022-07-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["officialid"]},
        ),
        migrations.AlterModelOptions(
            name="line",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="stationline",
            options={"ordering": ["internal_representation"]},
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["identification_no"]},
        ),
        migrations.AlterField(
            model_name="asset",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="operation.station",
            ),
        ),
        migrations.AlterField(
            model_name="stationline",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="station_lines",
                to="operation.line",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="operation.line",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_SERVICE", "In Service"),
                    ("NOT_SPOTTED", "Not Spotted"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("MARRIED", "Married"),
                    ("TESTING", "Testing"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=32,
            ),
        ),
    ]
