# Generated by Django 4.0.6 on 2022-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDER_MAINTENANCE", "Under Maintenance"),
                    ("IN_OPERATION", "In Operation"),
                ],
                default="IN_OPERATION",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
