# Generated by Django 4.0.6 on 2022-07-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0003_remove_stationline_display_name_line_stations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="stations",
            new_name="station",
        ),
    ]
