# Generated by Django 4.0.6 on 2022-07-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0003_vehicletype_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="internal_name",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
