# Generated by Django 4.0.6 on 2022-07-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0004_vehicletype_internal_name_alter_vehicle_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="in_service_since",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
