# Generated by Django 4.0.6 on 2022-07-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0004_rename_stations_asset_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="long_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="asset",
            name="officialid",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="short_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="line",
            name="code",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="internal_representation",
            field=models.CharField(
                blank=True, default=None, max_length=32, null=True, unique=True
            ),
        ),
    ]
