# Generated by Django 4.1 on 2022-08-14 05:35

from django.db import migrations


def forwards_func(apps, schema_editor):
    Vehicle = apps.get_model("operation", "Vehicle")
    VehicleLine = apps.get_model("operation", "VehicleLine")

    create_list = []
    for vehicle in Vehicle.objects.all():
        create_list.append(
            VehicleLine(
                vehicle_id=vehicle.id,
                line_id=vehicle.line_id,
            )
        )

    VehicleLine.objects.bulk_create(create_list)


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0004_vehicleline_many_to_many_db0"),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func, reverse_code=migrations.RunPython.noop
        ),
    ]
