# Generated by Django 4.0.6 on 2022-07-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operation",
            "0005_alter_asset_long_description_alter_asset_officialid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="short_description",
            field=models.CharField(blank=True, default="", max_length=96),
        ),
    ]
