# Generated by Django 4.0.6 on 2022-07-09 11:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0006_alter_asset_short_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="stations",
        ),
        migrations.RemoveField(
            model_name="station",
            name="lines",
        ),
        migrations.AddField(
            model_name="station",
            name="display_code",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=16, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="line",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="operation.line",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="station",
            name="display_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="station",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
        migrations.DeleteModel(
            name="StationLine",
        ),
    ]
