# Generated by Django 4.1 on 2022-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0007_alter_station_options_vehicle_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationline",
            name="override_internal_representation_constraint",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="line",
            name="code",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="stationline",
            name="internal_representation",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("officialid",), name="operation_asset_unique_officialid"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetmedia",
            constraint=models.UniqueConstraint(
                fields=("asset", "media"),
                name="operation_assetmedia_unique_asset_media",
            ),
        ),
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("code",), name="operation_line_unique_line_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("display_name",), name="operation_line_unique_display_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("display_name",), name="operation_station_unique_display_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="stationline",
            constraint=models.UniqueConstraint(
                fields=("station", "line"),
                name="operation_stationline_unique_station_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="stationline",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("override_internal_representation_constraint", False),
                        ("internal_representation__isnull", False),
                    )
                ),
                fields=("internal_representation",),
                name="operation_stationline_unique_internal_representation",
            ),
        ),
        migrations.AddConstraint(
            model_name="stationmedia",
            constraint=models.UniqueConstraint(
                fields=("station", "media"),
                name="operation_stationmedia_unique_station_media",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                fields=("identification_no", "vehicle_type"),
                name="operation_vehicle_unique_identification_no_vehicle_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleline",
            constraint=models.UniqueConstraint(
                fields=("vehicle", "line"),
                name="operation_vehicleline_unique_vehicle_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicletype",
            constraint=models.UniqueConstraint(
                fields=("internal_name",),
                name="operation_vehicletype_unique_internal_name",
            ),
        ),
    ]
