# Generated by Django 4.1 on 2022-08-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operation",
            "0008_stationline_override_internal_representation_constraint_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleline",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="operation.line"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleline",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="operation.vehicle"
            ),
        ),
    ]
