# Generated by Django 4.2 on 2023-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operation",
            "0011_stationline_operation_stationline_unique_line_internal_representation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_SERVICE", "In Service"),
                    ("NOT_SPOTTED", "Not Spotted"),
                    ("OUT_OF_SERVICE", "Out Of Service"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("MARRIED", "Married"),
                    ("TESTING", "Testing"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=32,
            ),
        ),
    ]
