# Generated by Django 4.2.3 on 2023-07-15 19:32

import django_choices_field.fields
from django.db import migrations

import operation.enums


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0012_alter_vehicle_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("TESTING", "Testing"),
                    ("DEFUNCT", "Defunct"),
                    ("ACTIVE", "Active"),
                    ("PARTIAL_ACTIVE", "Partial Active"),
                    ("PARTIAL_DISRUPTION", "Partial Disruption"),
                    ("TOTAL_DISRUPTION", "Total Disruption"),
                ],
                choices_enum=operation.enums.LineStatus,
                default="ACTIVE",
                max_length=32,
            ),
        ),
    ]
