# Generated by Django 4.2.3 on 2023-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0013_line_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="official_numbering",
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
