# Generated by Django 4.2.7 on 2023-11-10 11:42

import colorfield.fields
import django_choices_field.fields
from django.db import migrations

import operation.enums


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0014_line_official_numbering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="display_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="wheel_status",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("FRESH", "Fresh"),
                    ("NEAR_PERFECT", "Near Perfect"),
                    ("FLAT", "Flat"),
                    ("WORN_OUT", "Worn Out"),
                    ("WORRYING", "Worrying"),
                ],
                choices_enum=operation.enums.WheelStatus,
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
