# Generated by Django 4.2.19 on 2025-02-25 19:48

import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import operation.enums


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operation", "0016_line_calendar_incidents_line_telegram_channel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalVehicle",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("identification_no", models.CharField(max_length=16)),
                (
                    "nickname",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_SERVICE", "In Service"),
                            ("NOT_SPOTTED", "Not Spotted"),
                            ("OUT_OF_SERVICE", "Out Of Service"),
                            ("DECOMMISSIONED", "Decommissioned"),
                            ("MARRIED", "Married"),
                            ("TESTING", "Testing"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "wheel_status",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("FRESH", "Fresh"),
                            ("NEAR_PERFECT", "Near Perfect"),
                            ("FLAT", "Flat"),
                            ("WORN_OUT", "Worn Out"),
                            ("WORRYING", "Worrying"),
                        ],
                        choices_enum=operation.enums.WheelStatus,
                        default=None,
                        max_length=16,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "in_service_since",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operation.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vehicle",
                "verbose_name_plural": "historical vehicles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAsset",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "officialid",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("long_description", models.TextField(blank=True, default="")),
                (
                    "asset_type",
                    models.TextField(
                        choices=[("ESCALATOR", "Escalator"), ("LIFT", "Lift")]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("IN_OPERATION", "In Operation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operation.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset",
                "verbose_name_plural": "historical assets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
