# Generated by Django 4.2.3 on 2023-07-16 09:09

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import model_utils.fields
from django.db import migrations, models

import chartography.enums
import operation.enums


def add_data_sources(apps, schema_editor):
    Source = apps.get_model("chartography", "Source")
    sources = ["PRASARANA", "MLPTF", "MTREC", "MRFC"]

    Source.objects.bulk_create([Source(name=source) for source in sources])


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operation", "0013_line_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineVehicleStatusCountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("IN_SERVICE", "In Service"),
                            ("NOT_SPOTTED", "Not Spotted"),
                            ("OUT_OF_SERVICE", "Out Of Service"),
                            ("DECOMMISSIONED", "Decommissioned"),
                            ("MARRIED", "Married"),
                            ("TESTING", "Testing"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        choices_enum=operation.enums.VehicleStatus,
                        max_length=32,
                    ),
                ),
                ("count", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("url", models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("PRASARANA", "Prasarana"),
                            ("MLPTF", "Mlptf"),
                            ("MTREC", "Mtrec"),
                            ("MRFC", "Mrfc"),
                        ],
                        choices_enum=chartography.enums.DataSources,
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("official_site", models.URLField(blank=True, default=None, null=True)),
                ("icon_url", models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceCustomLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chartography.source",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("name",), name="chartography_source_unique_name"
            ),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chartography.source"
            ),
        ),
        migrations.AddField(
            model_name="linevehiclestatuscounthistory",
            name="custom_line",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="chartography.sourcecustomline",
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="linevehiclestatuscounthistory",
            name="line",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="operation.line",
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="linevehiclestatuscounthistory",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chartography.snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecustomline",
            constraint=models.UniqueConstraint(
                fields=("source", "name"),
                name="chartography_sourcecustomline_unique_source_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.UniqueConstraint(
                fields=("date", "source"),
                name="chartography_snapshot_unique_date_source",
            ),
        ),
        migrations.AddIndex(
            model_name="linevehiclestatuscounthistory",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["line", "status"], name="chartograph_line_id_4e6a10_btree"
            ),
        ),
        migrations.AddConstraint(
            model_name="linevehiclestatuscounthistory",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "line", "status"),
                name="chartography_linevehiclestatuscounthistory_unique_snapshot_line_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="linevehiclestatuscounthistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("line__isnull", True),
                    ("custom_line__isnull", True),
                    _connector="OR",
                ),
                name="chartography_linevehiclestatuscounthistory_line_custom_line_mutually_exclusive",
            ),
        ),
        migrations.RunPython(
            code=add_data_sources,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
