# Generated by Django 4.2.3 on 2023-07-15 21:15

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import model_utils.fields
from django.db import migrations, models

import operation.enums


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operation", "0013_line_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineVehicleStatusCountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("IN_SERVICE", "In Service"),
                            ("NOT_SPOTTED", "Not Spotted"),
                            ("OUT_OF_SERVICE", "Out Of Service"),
                            ("DECOMMISSIONED", "Decommissioned"),
                            ("MARRIED", "Married"),
                            ("TESTING", "Testing"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        choices_enum=operation.enums.VehicleStatus,
                        max_length=32,
                    ),
                ),
                ("count", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("name",), name="chartography_source_unique_name"
            ),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chartography.source"
            ),
        ),
        migrations.AddField(
            model_name="linevehiclestatuscounthistory",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="operation.line"
            ),
        ),
        migrations.AddField(
            model_name="linevehiclestatuscounthistory",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chartography.snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.UniqueConstraint(
                fields=("date", "source"),
                name="chartography_snapshot_unique_date_source",
            ),
        ),
        migrations.AddIndex(
            model_name="linevehiclestatuscounthistory",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["line", "status"], name="chartograph_line_id_4e6a10_btree"
            ),
        ),
        migrations.AddConstraint(
            model_name="linevehiclestatuscounthistory",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "line", "status"),
                name="chartography_linevehiclestatuscounthistory_unique_snapshot_line_status",
            ),
        ),
    ]
