# Generated by Django 4.2.3 on 2023-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chartography", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="linevehiclestatuscounthistory",
            name="chartography_linevehiclestatuscounthistory_unique_snapshot_line_status",
        ),
        migrations.AddConstraint(
            model_name="linevehiclestatuscounthistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("line__isnull", False)),
                fields=("snapshot", "line", "status"),
                name="chartography_linevehiclestatuscounthistory_unique_snapshot_line_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="linevehiclestatuscounthistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_line__isnull", False)),
                fields=("snapshot", "custom_line", "status"),
                name="chartography_linevehiclestatuscounthistory_unique_snapshot_custom_line_status",
            ),
        ),
    ]
