# Generated by Django 4.2.3 on 2023-07-18 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_alter_media_file"),
        (
            "chartography",
            "0002_remove_linevehiclestatuscounthistory_chartography_linevehiclestatuscounthistory_unique_snapshot_line",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="snapshot",
            name="chartography_snapshot_unique_date_source",
        ),
        migrations.AddField(
            model_name="snapshot",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("triggered_by__isnull", True)),
                fields=("date", "source"),
                name="chartography_snapshot_unique_date_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("triggered_by__isnull", False)),
                fields=("date", "source", "triggered_by"),
                name="chartography_snapshot_unique_date_source_w_user",
            ),
        ),
    ]
