# Generated by Django 4.2.8 on 2023-12-06 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0015_alter_line_display_color_vehicle_wheel_status"),
        (
            "chartography",
            "0003_remove_snapshot_chartography_snapshot_unique_date_source_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceCustomLineLineMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="operation.line"
                    ),
                ),
                (
                    "source_custom_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chartography.sourcecustomline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sourcecustomline",
            name="mapped_lines",
            field=models.ManyToManyField(
                through="chartography.SourceCustomLineLineMapping", to="operation.line"
            ),
        ),
    ]
