# Generated by Django 4.0.6 on 2022-07-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.media"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="medias",
            field=models.ManyToManyField(
                through="reporting.ReportMedia", to="common.media"
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="reportmedia",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reporting.report"
            ),
        ),
    ]
