# Generated by Django 4.0.6 on 2022-07-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operation",
            "0005_alter_asset_long_description_alter_asset_officialid_and_more",
        ),
        ("reporting", "0002_reportmedia_report_medias_resolution_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="operation.asset",
            ),
        ),
    ]
