# Generated by Django 4.1 on 2022-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationincident",
            name="is_last",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleincident",
            name="is_last",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stationincident",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="vehicleincident",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
    ]
