# Generated by Django 4.1 on 2022-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0002_stationincident_is_last_vehicleincident_is_last_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stationincident",
            constraint=models.UniqueConstraint(
                fields=("is_last", "station"),
                name="incident_stationincident_unique_is_last_station",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleincident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_last", True)),
                fields=("is_last", "vehicle"),
                name="incident_vehicleincident_unique_is_last_vehicle",
            ),
        ),
    ]
