# Generated by Django 4.2 on 2023-05-03 13:45

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_user_nickname"),
        ("operation", "0012_alter_vehicle_status"),
        (
            "incident",
            "0003_stationincident_incident_stationincident_unique_is_last_station_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarIncidentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="stationincident",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="vehicleincident",
            options={"ordering": ("order",)},
        ),
        migrations.CreateModel(
            name="CalendarIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("MINOR", "Minor"),
                            ("MILESTONE", "Milestone"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(default=None, max_length=64)),
                ("brief", models.CharField(default=None, max_length=256)),
                ("details", models.TextField(blank=True, default="")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="incident.calendarincidentcategory"
                    ),
                ),
                ("lines", models.ManyToManyField(blank=True, to="operation.line")),
                ("medias", models.ManyToManyField(blank=True, to="common.media")),
                (
                    "stations",
                    models.ManyToManyField(blank=True, to="operation.station"),
                ),
                (
                    "vehicles",
                    models.ManyToManyField(blank=True, to="operation.vehicle"),
                ),
                (
                    "impact_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Scores to deduct from full score of 100 per day. Will be prorated based on usual service hours when consolidating.",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
