# Generated by Django 4.2.1 on 2023-05-17 09:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0005_alter_calendarincident_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarincident",
            name="severity",
            field=models.CharField(
                choices=[
                    ("MAJOR", "Major"),
                    ("MINOR", "Minor"),
                    ("OTHERS", "Others"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CalendarIncidentChronology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "indicator",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green"),
                            ("RED", "Red"),
                            ("BLUE", "Blue"),
                            ("GRAY", "Gray"),
                            ("LOADING", "Loading"),
                        ],
                        help_text="Set the color of circles. Green means completed or success status, Red means warning or error, and Blue means ongoing or other default status, Gray for unfinished or disabled status, Loading for in progress status.",
                        max_length=16,
                    ),
                ),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "calendar_incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident.calendarincident",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CalendarIncidentChronologies",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
