# Generated by Django 4.2.1 on 2023-05-18 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0006_alter_calendarincident_severity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarincidentchronology",
            name="calendar_incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chronologies",
                to="incident.calendarincident",
            ),
        ),
        migrations.AlterField(
            model_name="calendarincidentchronology",
            name="indicator",
            field=models.CharField(
                choices=[
                    ("GREEN", "Green"),
                    ("RED", "Red"),
                    ("BLUE", "Blue"),
                    ("GRAY", "Gray"),
                ],
                help_text="Set the color of circles. Green means completed or success status, Red means warning or error, and Blue means ongoing or other default status, Gray for unfinished or disabled status, Loading for in progress status.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="calendarincidentchronology",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
    ]
