# Generated by Django 4.2.1 on 2023-05-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0008_alter_calendarincident_brief"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarincidentchronology",
            name="source_url",
            field=models.URLField(
                blank=True, default="", null=True, unique_for_date="datetime"
            ),
        ),
    ]
