# Generated by Django 4.2.1 on 2023-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0009_calendarincidentchronology_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarincident",
            name="inaccurate",
            field=models.BooleanField(
                default=False, help_text="Displays the 'inaccurate' indicator."
            ),
        ),
        migrations.AddField(
            model_name="calendarincident",
            name="long_term",
            field=models.BooleanField(
                default=False,
                help_text="If the incident is long-term, only start date will be shown in the month calendar view.",
            ),
        ),
    ]
