# Generated by Django 4.2.3 on 2023-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0011_calendarincidentmedia_alter_calendarincident_medias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarincidentchronology",
            name="source_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
