# Generated by Django 5.2.17 on 2026-08-21 18:06

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


def seed_just_reporting_category(apps, schema_editor):
    CalendarIncidentCategory = apps.get_model("incident", "CalendarIncidentCategory")
    CalendarIncidentCategory.objects.get_or_create(name="Just Reporting")


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("incident", "0013_alter_calendarincident_lines"),
        ("operation", "0017_historicalvehicle_historicalasset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, default="", max_length=256)),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="incident.calendarincidentcategory"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_social_media_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("lines", models.ManyToManyField(blank=True, to="operation.line")),
                (
                    "stations",
                    models.ManyToManyField(blank=True, to="operation.station"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicles",
                    models.ManyToManyField(blank=True, to="operation.vehicle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(seed_just_reporting_category, migrations.RunPython.noop),
    ]
