# Generated by Django 5.2.17 on 2026-08-21 21:25

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0016_calendarincidentchronology_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarincident",
            name="severity",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("MAJOR", "Major"), ("MINOR", "Minor"), ("OTHERS", "Others")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="calendarincidentchronology",
            name="indicator",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("GREEN", "Green"),
                    ("RED", "Red"),
                    ("BLUE", "Blue"),
                    ("GRAY", "Gray"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalendarincident",
            name="severity",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("MAJOR", "Major"), ("MINOR", "Minor"), ("OTHERS", "Others")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalendarincidentchronology",
            name="indicator",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("GREEN", "Green"),
                    ("RED", "Red"),
                    ("BLUE", "Blue"),
                    ("GRAY", "Gray"),
                ],
                max_length=5,
            ),
        ),
    ]
