# Generated by Django 5.2.17 on 2026-08-22 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_vote_user'),
        ('incident', '0017_fix_text_choices_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user'),
        ),
    ]
