# Generated by Django 5.2.17 on 2026-08-22 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_vote_user'),
        ('incident', '0018_alter_socialmedialink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_social_media_links', to='common.user'),
        ),
    ]
