# Generated by Django 5.2.17 on 2026-08-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_alter_vote_user"),
        ("incident", "0020_calendarincident_created_by_and_more"),
        ("operation", "0017_historicalvehicle_historicalasset"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stationincident",
            name="incident_stationincident_unique_is_last_station",
        ),
        migrations.AddConstraint(
            model_name="stationincident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_last", True)),
                fields=("is_last", "station"),
                name="incident_stationincident_unique_is_last_station",
            ),
        ),
    ]
