# Generated by Django 5.2.17 on 2026-09-03 01:31

import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0021_remove_stationincident_incident_stationincident_unique_is_last_station_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialink",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("live", "Live"), ("pending_approval", "Pending Approval")],
                default="pending_approval",
                max_length=16,
            ),
        ),
    ]
