# Generated by Django 5.2.17 on 2026-09-03 02:08

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0022_socialmedialink_description_socialmedialink_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarincident",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("live", "Live"),
                    ("rejected", "Rejected"),
                    ("pending_deletion", "Pending Deletion"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="calendarincidentchronology",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("live", "Live"),
                    ("rejected", "Rejected"),
                    ("pending_deletion", "Pending Deletion"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalendarincident",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("live", "Live"),
                    ("rejected", "Rejected"),
                    ("pending_deletion", "Pending Deletion"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalendarincidentchronology",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("live", "Live"),
                    ("rejected", "Rejected"),
                    ("pending_deletion", "Pending Deletion"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
