# Generated by Django 5.2.17 on 2026-09-21 23:20

import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import model_utils.fields
from django.db import migrations, models

BATCH_SIZE = 500


def backfill_normalized_urls(apps, schema_editor):
    from incident.services.urls import canonicalize_url

    SocialMediaLink = apps.get_model("incident", "SocialMediaLink")
    batch = []
    for link in SocialMediaLink.objects.all().iterator():
        link.normalized_url = canonicalize_url(link.url) or None
        batch.append(link)
        if len(batch) >= BATCH_SIZE:
            SocialMediaLink.objects.bulk_update(batch, ["normalized_url"])
            batch = []
    if batch:
        SocialMediaLink.objects.bulk_update(batch, ["normalized_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_media_caption_media_duration_and_more"),
        ("incident", "0023_alter_calendarincident_status_and_more"),
        ("operation", "0017_historicalvehicle_historicalasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialink",
            name="normalized_url",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=2048, null=True
            ),
        ),
        migrations.RunPython(backfill_normalized_urls, migrations.RunPython.noop),
        migrations.CreateModel(
            name="LineStatusReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("BUSY", "Busy"),
                            ("CROWDED", "Crowded"),
                            ("EXTREMELY_CROWDED", "Extremely Crowded"),
                            ("BACKLOGGED", "Backlogged"),
                            ("DELAYED", "Delayed"),
                            ("DISRUPTED", "Disrupted"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "delay_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_reports",
                        to="operation.line",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_reports",
                        to="incident.socialmedialink",
                    ),
                ),
                (
                    "stations",
                    models.ManyToManyField(blank=True, to="operation.station"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_status_reports",
                        to="common.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
