# Generated by Django 5.2.17 on 2026-09-22 01:55

from django.db import migrations

BATCH_SIZE = 500


def rebackfill_normalized_urls(apps, schema_editor):
    from incident.services.urls import canonicalize_url

    SocialMediaLink = apps.get_model("incident", "SocialMediaLink")
    batch = []
    for link in SocialMediaLink.objects.all().iterator():
        link.normalized_url = canonicalize_url(link.url) or None
        batch.append(link)
        if len(batch) >= BATCH_SIZE:
            SocialMediaLink.objects.bulk_update(batch, ["normalized_url"])
            batch = []
    if batch:
        SocialMediaLink.objects.bulk_update(batch, ["normalized_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0024_socialmedialink_normalized_url_linestatusreport"),
    ]

    operations = [
        migrations.RunPython(rebackfill_normalized_urls, migrations.RunPython.noop),
    ]
