# Generated by Django 5.2.17 on 2026-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_media_caption_media_duration_and_more"),
        ("incident", "0025_rebackfill_normalized_url"),
        ("operation", "0017_historicalvehicle_historicalasset"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="linestatusreport",
            index=models.Index(
                fields=["line", "created"], name="incident_li_line_id_828375_idx"
            ),
        ),
    ]
