# Generated by Django 5.2.17 on 2026-09-26 16:12

import django_choices_field.fields
from django.db import migrations, models


def seed_system_author(apps, schema_editor):
    """Create the system author that automated posts are attributed to.

    ``SocialMediaLink.user`` is non-null and automated ingestion has no human
    actor, so the row is seeded here rather than requested at write time.
    get_or_create keeps the migration replay-safe.
    """
    User = apps.get_model("common", "User")
    User.objects.get_or_create(
        firebase_id="system:official-ingest",
        defaults={"nickname": "Official Post Ingestion"},
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_media_caption_media_duration_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("incident", "0026_linestatusreport_incident_li_line_id_828375_idx"),
        ("operation", "0017_historicalvehicle_historicalasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialink",
            name="is_automated",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="platform",
            field=django_choices_field.fields.TextChoicesField(
                blank=True, choices=[("x", "X")], default=None, max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="post_id",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="posted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="source_handle",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="socialmedialink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("platform__isnull", False), ("post_id__isnull", False)
                ),
                fields=("platform", "post_id"),
                name="socialmedialink_unique_platform_post",
            ),
        ),
        migrations.RunPython(seed_system_author, migrations.RunPython.noop),
    ]
