# Generated by Django 5.2.17 on 2026-09-28 18:59

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0027_socialmedialink_is_automated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedialink",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("live", "Live"),
                    ("pending_approval", "Pending Approval"),
                    ("hidden", "Hidden"),
                ],
                default="pending_approval",
                max_length=16,
            ),
        ),
    ]
