# Generated by Django 5.2.17 on 2026-09-28 22:24
"""Agency + SocMedAccount registry; SocialMediaLink moves to the account.

Forward: schema for the two registry models, then the ``socmed_account`` FK on
``SocialMediaLink``, then a data migration that seeds the registry (the two
tracked X accounts with their full provider user objects baked in, so
staging/prod seeds cost no API calls) and backfills every pre-existing
automated row onto the matching account, then the removal of the legacy
denormalized ``platform`` + ``source_handle`` columns and their constraint, and
finally the new ``(socmed_account, post_id)`` partial unique constraint (data
before removals: the backfill still needs the legacy columns readable).

Reverse: the data half is a deliberate noop — the schema operations above are
all reversible by Django, but un-seeding would need to distinguish rows the
migration created from pre-existing ones.
"""

from datetime import datetime

import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import model_utils.fields
from django.db import migrations, models


def seed_registry(apps, schema_editor):
    """Seed the Agency / SocMedAccount registry and backfill legacy rows.

    1. ``get_or_create`` the two agencies: "Prasarana Malaysia Berhad" (the
       only tracked operator today) and "Unassigned" (the target for accounts
       ``services/official_posts.resolve_account`` auto-registers before a
       human maps them to a real operator).
    2. ``get_or_create`` the two X accounts the pipeline tracks, with their
       full provider user objects baked in as literals (fetched 2026-09-28 from
       ``GET /2/users/by/username/{handle}?user.fields=id,username,name,
       description,created_at,location,url,profile_image_url,public_metrics,
       verified,verified_type``) — same shape ``ensure_user_profile`` persists
       on a live lookup, so seeding and resolving cannot diverge.
    3. Backfill: for every existing ``SocialMediaLink`` row that still carries
       its legacy ``(platform, source_handle)``, ``get_or_create`` the matching
       account (known handles -> Prasarana, anything else -> Unassigned) and
       point the row's ``socmed_account`` at it. Queryset ``.update()`` keeps
       this lean, and it is a no-op on an empty table.

    ``get_or_create`` everywhere keeps the migration replay-safe across
    partially-migrated databases.
    """
    Agency = apps.get_model("incident", "Agency")
    SocMedAccount = apps.get_model("incident", "SocMedAccount")
    SocialMediaLink = apps.get_model("incident", "SocialMediaLink")

    prasarana, _ = Agency.objects.get_or_create(
        name="Prasarana Malaysia Berhad",
        defaults={
            "short_name": "Prasarana",
            "description": (
                "Malaysia's largest public transport operator; owns and runs "
                "the Rapid KL rail and bus networks."
            ),
            "website": "https://www.prasarana.com.my",
        },
    )
    unassigned, _ = Agency.objects.get_or_create(
        name="Unassigned",
        defaults={
            "short_name": "",
            "description": (
                "Auto-registered accounts pending mapping to a real agency."
            ),
            "website": "",
        },
    )

    # (handle, user_id, display_name, raw_payload) — provider ``data`` objects
    # from GET /2/users/by/username/{handle} (fetched 2026-09-28).
    askrapidkl_payload = {
        "created_at": "2014-12-18T04:20:20.000Z",
        "description": "🟥🟦 The official X account of Rapid KL\nFollow Rapid KL WhatsApp Channel: https://t.co/baIG7YTgxJ",
        "id": "2934256998",
        "name": "Ask Rapid KL",
        "profile_image_url": "https://pbs.twimg.com/profile_images/553484624806965251/HXivzvXw_normal.png",
        "public_metrics": {
            "followers_count": 103574,
            "following_count": 39,
            "like_count": 413,
            "listed_count": 95,
            "media_count": 12690,
            "tweet_count": 552248,
        },
        "url": "https://t.co/Zao4iDtYEQ",
        "username": "askrapidkl",
        "verified": False,
        "verified_type": "none",
    }
    myrapidkl_payload = {
        "created_at": "2021-03-26T07:38:10.000Z",
        "description": "Rapid KL by Prasarana OFFICIAL X Account. For support & queries, pls contact: @AskRapidKL 6 am - 12 am daily. Pls read our House Rule https://t.co/VmBl4OD0rW",
        "id": "1375351250745618432",
        "location": "3.1134737085984336, 101.585351",
        "name": "Rapid KL",
        "profile_image_url": "https://pbs.twimg.com/profile_images/1386964899318755329/5yCcZMFJ_normal.jpg",
        "public_metrics": {
            "followers_count": 8773,
            "following_count": 75,
            "like_count": 195,
            "listed_count": 15,
            "media_count": 3977,
            "tweet_count": 7766,
        },
        "url": "https://t.co/LQjBdRWzLb",
        "username": "myrapidkl",
        "verified": False,
        "verified_type": "none",
    }
    seeded = [
        ("askrapidkl", "2934256998", "Ask Rapid KL", askrapidkl_payload),
        ("myrapidkl", "1375351250745618432", "Rapid KL", myrapidkl_payload),
    ]
    for handle, user_id, display_name, raw_payload in seeded:
        SocMedAccount.objects.get_or_create(
            platform="x",
            handle=handle,
            defaults={
                "agency": prasarana,
                "user_id": user_id,
                "display_name": display_name,
                "raw_payload": raw_payload,
                "is_enabled": True,
                # Profile fetched 2026-09-28 (naive local, matching
                # TIME_ZONE="Asia/Kuala_Lumpur" with USE_TZ=False).
                "resolved_at": datetime(2026, 9, 28, 8, 0, 0),
            },
        )

    # Backfill: legacy (platform, source_handle) -> socmed_account.
    legacy_rows = (
        SocialMediaLink.objects.exclude(source_handle="")
        .exclude(platform__isnull=True)
        .values("platform", "source_handle")
        .distinct()
    )
    known = {"askrapidkl": prasarana, "myrapidkl": prasarana}
    for row in legacy_rows:
        handle = str(row["source_handle"] or "").strip().lstrip("@")
        if not handle:
            continue
        agency = known.get(handle.lower(), unassigned)
        account, _ = SocMedAccount.objects.get_or_create(
            platform=row["platform"],
            handle=handle,
            defaults={"agency": agency, "is_enabled": True},
        )
        SocialMediaLink.objects.filter(
            platform=row["platform"], source_handle=row["source_handle"]
        ).update(socmed_account=account)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_media_caption_media_duration_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("incident", "0028_alter_socialmedialink_status"),
        ("operation", "0017_historicalvehicle_historicalasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("short_name", models.CharField(blank=True, default="", max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                ("website", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "agencies",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SocMedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "platform",
                    django_choices_field.fields.TextChoicesField(
                        choices=[("x", "X")], max_length=1
                    ),
                ),
                ("handle", models.CharField(max_length=64)),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "ordering": ("platform", "handle"),
            },
        ),
        migrations.AddField(
            model_name="socmedaccount",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="socmed_accounts",
                to="incident.agency",
            ),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="socmed_account",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links",
                to="incident.socmedaccount",
            ),
        ),
        migrations.RunPython(seed_registry, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="socialmedialink",
            name="socialmedialink_unique_platform_post",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="source_handle",
        ),
        migrations.AddConstraint(
            model_name="socialmedialink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("post_id__isnull", False), ("socmed_account__isnull", False)
                ),
                fields=("socmed_account", "post_id"),
                name="socialmedialink_unique_account_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="socmedaccount",
            constraint=models.UniqueConstraint(
                fields=("platform", "handle"),
                name="socmedaccount_unique_platform_handle",
            ),
        ),
        migrations.AddConstraint(
            model_name="socmedaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_id__gt", "")),
                fields=("platform", "user_id"),
                name="socmedaccount_unique_platform_user_id",
            ),
        ),
    ]
