# Generated by Django 5.2.17 on 2026-09-30 19:29
"""SocialMediaLink: ``occurred_at`` (display datetime) + ``thread`` (grouping).

``occurred_at`` is the user-facing "when did this happen" instant that every
feed/queue ordering and the keyset cursor are built on; ``created`` remains the
provenance column ("when did someone report this?"). It is added NON-NULL on
purpose — keyset pagination on ``-occurred_at, -id`` needs a *total* order, and a
nullable column would force ``Coalesce`` into every filter and ``.order_by()``.

``thread`` is the self-referencing grouping FK. A thread is represented by its
ROOT row (``thread_id is None``); members point at the root through
``thread_members``. The invariant "``thread`` always points at a ROOT" is enforced
by the grouping service, not here, and ``on_delete=SET_NULL`` is deliberate: a
deleted root un-threads its members rather than cascade-deleting the group.

The data backfill runs BEFORE the composite index is built so the btree is
populated from final values instead of being churned by the UPDATE.

Forward: ``occurred_at = COALESCE(posted_at, created)``. An automated row's real
post time wins, because that is the instant the event happened; everything else
falls back to its creation time, which is the closest thing a hand-submitted
link has to an "occurred" value.
Reverse: ``occurred_at = created``. That is deliberately lossy-but-safe rather
than exact — there is no way to recover "which rows had a ``posted_at``" from
``occurred_at`` alone once the backfill has run, and re-deriving
``COALESCE(posted_at, created)`` in reverse would *re-introduce* the shift for
rows whose ``occurred_at`` was deliberately re-set to something custom (the
``Some(None) → link.created`` reset in the update service). Falling back to
``created`` restores the pre-0030 ordering semantics, which is exactly what
reverting a migration means. ``posted_at`` is never read-modified-written in
either direction: this migration has no destructive half.

TIMEZONE TRAP — why this is a raw SQL COALESCE and not a Python loop
--------------------------------------------------------------------
``USE_TZ = False`` with ``TIME_ZONE = "Asia/Kuala_Lumpur"`` (see MISTAKES.md
2026-09-26, "an exported ``posted_at`` is naive **local** time"). Every datetime
column in this table already holds naive LOCAL wall time: ingestion stores an
aware UTC value through the ORM, and the ORM drops the tzinfo and shifts it into
the local frame on the way in. So ``posted_at`` and ``created`` are already in the
*same* frame and the backfill is a straight copy.

There must be NO ``make_aware`` / ``make_naive`` / ``astimezone`` / ``localtime``
anywhere near this. Calling one would shift every value by +08:00, and because
the UI renders minute precision the shift is invisible on screen — it would only
surface later as links ordered into the wrong calendar day against the service-day
window. The same applies to a Python ``for link in ...: link.occurred_at = ...
bulk_update(...)`` loop: it round-trips each value through the field adapter,
which is exactly the conversion ``USE_TZ=True`` would perform, so the safety is
structural here — a single SQL ``COALESCE`` moves the stored bytes and can never
be re-interpreted in another frame.
"""

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Coalesce


def backfill_occurred_at(apps, schema_editor):
    """Seed ``occurred_at`` from the real post time, else the creation time.

    Single UPDATE: no Python-side read/modify/write, so the stored bytes are
    copied verbatim and no timezone conversion can be interleaved (see the
    module docstring). Idempotent — re-running on an already-backfilled table
    recomputes the same value for rows that still have a ``posted_at`` and would
    clobber a hand-edited ``occurred_at`` on the others, so it must only ever be
    driven by the migration executor, never by a periodic job.
    """
    SocialMediaLink = apps.get_model("incident", "SocialMediaLink")
    SocialMediaLink.objects.all().update(occurred_at=Coalesce("posted_at", "created"))


def revert_occurred_at_to_created(apps, schema_editor):
    """Reverse half: pin ``occurred_at`` back to ``created`` for every row.

    Non-destructive and non-nullable by construction (``created`` is NOT NULL),
    so the reverse needs no per-row special-casing. ``posted_at`` is left exactly
    as it was found.
    """
    SocialMediaLink = apps.get_model("incident", "SocialMediaLink")
    SocialMediaLink.objects.all().update(occurred_at=F("created"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_media_caption_media_duration_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("incident", "0029_agency_socmedaccount_and_more"),
        ("operation", "0017_historicalvehicle_historicalasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialink",
            name="occurred_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="thread_members",
                to="incident.socialmedialink",
            ),
        ),
        migrations.RunPython(backfill_occurred_at, revert_occurred_at_to_created),
        migrations.AddIndex(
            model_name="socialmedialink",
            index=models.Index(
                fields=["-occurred_at", "-id"], name="socialmedialink_occurred_idx"
            ),
        ),
    ]
