replicaCount: 1

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

#################################
#################################
#################################

containers:
  web:
    image: nginx:alpine
    containerPort: 8000
  app:
    image: ghcr.io/kwongtn/lift-rosak-backend:1dc9838-16
    containerPort: 8001
    dbPassword:
      secret: postgres-django-postgresql-ha-postgresql
      key: password

volumes:
  web:
    configMap: backend-django-nginx-cm
  app:
    env:
      configMap: backend-django-cm
      secret: backend-django-sec

    firebaseAdminKeySecret: firebase-admin

topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
