name: Delete old container images

on:
  schedule:
    - cron: "0 0 1 * *" # the first day of the month

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: lift-rosak-backend
          filter-tags: ".*-(dev|fix)-.*"
          cut-off: One month ago UTC
          keep-at-least: 5
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
