name: Create and publish a Docker image to ghcr.io

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Buildx (push image)
        run: |
          docker buildx build \
            --platform ${{ DOCKER_TARGET_PLATFORM }} \
            --tag ${{ REGISTRY }}/${{ IMAGE_NAME }}:${{ GITHUB_SHA }}_${{ DOCKER_TARGET_PLATFORM }} \
            --file ./Dockerfile \
            --output type=image,push=true .
